name: 'CLA Assistant'
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: 'CLA Assistant'
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Alpha Release
        uses: gnosis/github-action@master
        # GitHub token, automatically provided to the action
        # (No need to define this secret in the repo settings)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-cla-document: 'https://github.com/gnosis/safe-react/blob/master/GNOSISCLA.md'
          branch: 'cla-signatures'
          allowlist: lukasschor,mikheevm,rmeissner,germartinez,fernandomg,Agupane,nicosampler,matextrem,gabitoesmiapodo,davidalbela,alongoni,Uxio0,dasanra,miguelmota,francovenica,tschubotz,luarx,giacomolicari,gnosis-info,bot*,katspaugh
          empty-commit-flag: false
          blockchain-storage-flag: false
